//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeList.Resources.Strings {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeList.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Common_OK => ResourceManager.GetString("Common_OK", resourceCulture);
        internal static string Common_Cancel => ResourceManager.GetString("Common_Cancel", resourceCulture);
        internal static string Common_Delete => ResourceManager.GetString("Common_Delete", resourceCulture);
        internal static string Common_CreateButton => ResourceManager.GetString("Common_CreateButton", resourceCulture);
        internal static string Common_FolderNotSelectedTitle => ResourceManager.GetString("Common_FolderNotSelectedTitle", resourceCulture);
        internal static string Common_FolderNotSelectedMessage => ResourceManager.GetString("Common_FolderNotSelectedMessage", resourceCulture);
        internal static string Common_SaveSuccessTitle => ResourceManager.GetString("Common_SaveSuccessTitle", resourceCulture);
        internal static string Common_SaveSuccessMessage => ResourceManager.GetString("Common_SaveSuccessMessage", resourceCulture);
        internal static string Common_SaveFailureTitle => ResourceManager.GetString("Common_SaveFailureTitle", resourceCulture);
        internal static string Common_SaveFailureMessage => ResourceManager.GetString("Common_SaveFailureMessage", resourceCulture);
        internal static string Common_SelectFolderPickerTitle => ResourceManager.GetString("Common_SelectFolderPickerTitle", resourceCulture);
        internal static string Common_AddNewFolderButton => ResourceManager.GetString("Common_AddNewFolderButton", resourceCulture);
        internal static string Common_FolderCreatePromptTitle => ResourceManager.GetString("Common_FolderCreatePromptTitle", resourceCulture);
        internal static string Common_FolderCreatePromptMessage => ResourceManager.GetString("Common_FolderCreatePromptMessage", resourceCulture);

        internal static string Tab_Create => ResourceManager.GetString("Tab_Create", resourceCulture);
        internal static string Tab_Scan => ResourceManager.GetString("Tab_Scan", resourceCulture);
        internal static string Tab_Folder => ResourceManager.GetString("Tab_Folder", resourceCulture);
        internal static string Tab_History => ResourceManager.GetString("Tab_History", resourceCulture);

        internal static string Folder_Description => ResourceManager.GetString("Folder_Description", resourceCulture);
        internal static string Folder_NewFolderToolbar => ResourceManager.GetString("Folder_NewFolderToolbar", resourceCulture);
        internal static string Folder_EmptyView => ResourceManager.GetString("Folder_EmptyView", resourceCulture);

        internal static string FolderDetail_Title => ResourceManager.GetString("FolderDetail_Title", resourceCulture);
        internal static string FolderDetail_Description => ResourceManager.GetString("FolderDetail_Description", resourceCulture);
        internal static string FolderDetail_EmptyView => ResourceManager.GetString("FolderDetail_EmptyView", resourceCulture);

        internal static string History_Description => ResourceManager.GetString("History_Description", resourceCulture);
        internal static string History_DeleteAllToolbar => ResourceManager.GetString("History_DeleteAllToolbar", resourceCulture);
        internal static string History_EmptyView => ResourceManager.GetString("History_EmptyView", resourceCulture);
        internal static string History_DeleteAllConfirmTitle => ResourceManager.GetString("History_DeleteAllConfirmTitle", resourceCulture);
        internal static string History_DeleteAllConfirmMessage => ResourceManager.GetString("History_DeleteAllConfirmMessage", resourceCulture);

        internal static string CreateMenu_Description => ResourceManager.GetString("CreateMenu_Description", resourceCulture);
        internal static string CreateMenu_Gs1Title => ResourceManager.GetString("CreateMenu_Gs1Title", resourceCulture);
        internal static string CreateMenu_Gs1Subtitle => ResourceManager.GetString("CreateMenu_Gs1Subtitle", resourceCulture);

        internal static string Scan_HeaderTitle => ResourceManager.GetString("Scan_HeaderTitle", resourceCulture);
        internal static string Scan_ResultTitle => ResourceManager.GetString("Scan_ResultTitle", resourceCulture);
        internal static string Scan_RawDataLabel => ResourceManager.GetString("Scan_RawDataLabel", resourceCulture);
        internal static string Scan_BarcodeTypeLabel => ResourceManager.GetString("Scan_BarcodeTypeLabel", resourceCulture);
        internal static string Scan_KindGs1 => ResourceManager.GetString("Scan_KindGs1", resourceCulture);
        internal static string Scan_KindNormal => ResourceManager.GetString("Scan_KindNormal", resourceCulture);
        internal static string Scan_Gs1ReliabilityText => ResourceManager.GetString("Scan_Gs1ReliabilityText", resourceCulture);
        internal static string Scan_AiAnalysisTitle => ResourceManager.GetString("Scan_AiAnalysisTitle", resourceCulture);
        internal static string Scan_SaveButton => ResourceManager.GetString("Scan_SaveButton", resourceCulture);

        internal static string Create_TypeLabel => ResourceManager.GetString("Create_TypeLabel", resourceCulture);
        internal static string Create_ValueLabel => ResourceManager.GetString("Create_ValueLabel", resourceCulture);
        internal static string Create_SelectFormatError => ResourceManager.GetString("Create_SelectFormatError", resourceCulture);
        internal static string Create_EnterValueError => ResourceManager.GetString("Create_EnterValueError", resourceCulture);
        internal static string Create_DefaultTitle => ResourceManager.GetString("Create_DefaultTitle", resourceCulture);
        internal static string Create_TitleFormat => ResourceManager.GetString("Create_TitleFormat", resourceCulture);

        internal static string Result_DefaultTitle => ResourceManager.GetString("Result_DefaultTitle", resourceCulture);
        internal static string Result_TitleFormat => ResourceManager.GetString("Result_TitleFormat", resourceCulture);
        internal static string Result_Preview => ResourceManager.GetString("Result_Preview", resourceCulture);
        internal static string Result_RawData => ResourceManager.GetString("Result_RawData", resourceCulture);
        internal static string Result_FormatLabelFormat => ResourceManager.GetString("Result_FormatLabelFormat", resourceCulture);
        internal static string Result_SaveFolderLabel => ResourceManager.GetString("Result_SaveFolderLabel", resourceCulture);
        internal static string Result_SaveButton => ResourceManager.GetString("Result_SaveButton", resourceCulture);

        internal static string Gs1Create_Title => ResourceManager.GetString("Gs1Create_Title", resourceCulture);
        internal static string Gs1Create_Description => ResourceManager.GetString("Gs1Create_Description", resourceCulture);
        internal static string Gs1Create_AddSectionTitle => ResourceManager.GetString("Gs1Create_AddSectionTitle", resourceCulture);
        internal static string Gs1Create_AiCodeLabel => ResourceManager.GetString("Gs1Create_AiCodeLabel", resourceCulture);
        internal static string Gs1Create_AiCodePlaceholder => ResourceManager.GetString("Gs1Create_AiCodePlaceholder", resourceCulture);
        internal static string Gs1Create_ValuePlaceholder => ResourceManager.GetString("Gs1Create_ValuePlaceholder", resourceCulture);
        internal static string Gs1Create_AddButton => ResourceManager.GetString("Gs1Create_AddButton", resourceCulture);
        internal static string Gs1Create_ElementsListTitle => ResourceManager.GetString("Gs1Create_ElementsListTitle", resourceCulture);
        internal static string Gs1Create_ReferenceTitle => ResourceManager.GetString("Gs1Create_ReferenceTitle", resourceCulture);
        internal static string Gs1Create_ReferenceDescription => ResourceManager.GetString("Gs1Create_ReferenceDescription", resourceCulture);
        internal static string Gs1Create_NoElementsError => ResourceManager.GetString("Gs1Create_NoElementsError", resourceCulture);

        internal static string Gs1Result_Title => ResourceManager.GetString("Gs1Result_Title", resourceCulture);
        internal static string Gs1Result_AiCodeTitle => ResourceManager.GetString("Gs1Result_AiCodeTitle", resourceCulture);
        internal static string Gs1Result_FormatLabel => ResourceManager.GetString("Gs1Result_FormatLabel", resourceCulture);
        internal static string Gs1Result_SaveButton => ResourceManager.GetString("Gs1Result_SaveButton", resourceCulture);

        internal static string AiName_01 => ResourceManager.GetString("AiName_01", resourceCulture);
        internal static string AiName_10 => ResourceManager.GetString("AiName_10", resourceCulture);
        internal static string AiName_11 => ResourceManager.GetString("AiName_11", resourceCulture);
        internal static string AiName_15 => ResourceManager.GetString("AiName_15", resourceCulture);
        internal static string AiName_17 => ResourceManager.GetString("AiName_17", resourceCulture);
        internal static string AiName_21 => ResourceManager.GetString("AiName_21", resourceCulture);
        internal static string AiName_30 => ResourceManager.GetString("AiName_30", resourceCulture);
        internal static string AiName_3100 => ResourceManager.GetString("AiName_3100", resourceCulture);
        internal static string AiName_3101 => ResourceManager.GetString("AiName_3101", resourceCulture);
        internal static string AiName_3102 => ResourceManager.GetString("AiName_3102", resourceCulture);
        internal static string AiName_3103 => ResourceManager.GetString("AiName_3103", resourceCulture);
        internal static string AiName_Unknown => ResourceManager.GetString("AiName_Unknown", resourceCulture);

        internal static string AiHint_01 => ResourceManager.GetString("AiHint_01", resourceCulture);
        internal static string AiHint_TextMax20 => ResourceManager.GetString("AiHint_TextMax20", resourceCulture);
        internal static string AiHint_Date => ResourceManager.GetString("AiHint_Date", resourceCulture);
        internal static string AiHint_30 => ResourceManager.GetString("AiHint_30", resourceCulture);
        internal static string AiHint_Weight => ResourceManager.GetString("AiHint_Weight", resourceCulture);

        internal static string AiValidate_EnterValue => ResourceManager.GetString("AiValidate_EnterValue", resourceCulture);
        internal static string AiValidate_01 => ResourceManager.GetString("AiValidate_01", resourceCulture);
        internal static string AiValidate_DateFormat => ResourceManager.GetString("AiValidate_DateFormat", resourceCulture);
        internal static string AiValidate_30 => ResourceManager.GetString("AiValidate_30", resourceCulture);
        internal static string AiValidate_Weight => ResourceManager.GetString("AiValidate_Weight", resourceCulture);
        internal static string AiValidate_MaxLength20 => ResourceManager.GetString("AiValidate_MaxLength20", resourceCulture);
        internal static string AiCode_EnterCode => ResourceManager.GetString("AiCode_EnterCode", resourceCulture);
        internal static string AiCode_InvalidFormat => ResourceManager.GetString("AiCode_InvalidFormat", resourceCulture);

        internal static string Format_QrCode_Name => ResourceManager.GetString("Format_QrCode_Name", resourceCulture);
        internal static string Format_QrCode_Placeholder => ResourceManager.GetString("Format_QrCode_Placeholder", resourceCulture);
        internal static string Format_FreeText_Hint => ResourceManager.GetString("Format_FreeText_Hint", resourceCulture);
        internal static string Format_Code128_Name => ResourceManager.GetString("Format_Code128_Name", resourceCulture);
        internal static string Format_AlphaNumPlaceholder => ResourceManager.GetString("Format_AlphaNumPlaceholder", resourceCulture);
        internal static string Format_AsciiOnly_Hint => ResourceManager.GetString("Format_AsciiOnly_Hint", resourceCulture);
        internal static string Format_Code39_Name => ResourceManager.GetString("Format_Code39_Name", resourceCulture);
        internal static string Format_Code39_Placeholder => ResourceManager.GetString("Format_Code39_Placeholder", resourceCulture);
        internal static string Format_Code39_Hint => ResourceManager.GetString("Format_Code39_Hint", resourceCulture);
        internal static string Format_Ean13_Name => ResourceManager.GetString("Format_Ean13_Name", resourceCulture);
        internal static string Format_Ean13_Placeholder => ResourceManager.GetString("Format_Ean13_Placeholder", resourceCulture);
        internal static string Format_Ean13_Hint => ResourceManager.GetString("Format_Ean13_Hint", resourceCulture);
        internal static string Format_Ean8_Name => ResourceManager.GetString("Format_Ean8_Name", resourceCulture);
        internal static string Format_Ean8_Placeholder => ResourceManager.GetString("Format_Ean8_Placeholder", resourceCulture);
        internal static string Format_Ean8_Hint => ResourceManager.GetString("Format_Ean8_Hint", resourceCulture);
        internal static string Format_UpcA_Name => ResourceManager.GetString("Format_UpcA_Name", resourceCulture);
        internal static string Format_UpcA_Placeholder => ResourceManager.GetString("Format_UpcA_Placeholder", resourceCulture);
        internal static string Format_UpcA_Hint => ResourceManager.GetString("Format_UpcA_Hint", resourceCulture);
        internal static string Format_Itf_Name => ResourceManager.GetString("Format_Itf_Name", resourceCulture);
        internal static string Format_Itf_Placeholder => ResourceManager.GetString("Format_Itf_Placeholder", resourceCulture);
        internal static string Format_Itf_Hint => ResourceManager.GetString("Format_Itf_Hint", resourceCulture);
        internal static string Format_Codabar_Name => ResourceManager.GetString("Format_Codabar_Name", resourceCulture);
        internal static string Format_Codabar_Placeholder => ResourceManager.GetString("Format_Codabar_Placeholder", resourceCulture);
        internal static string Format_Codabar_Hint => ResourceManager.GetString("Format_Codabar_Hint", resourceCulture);
        internal static string Format_Code93_Name => ResourceManager.GetString("Format_Code93_Name", resourceCulture);
        internal static string Format_DataMatrix_Name => ResourceManager.GetString("Format_DataMatrix_Name", resourceCulture);
        internal static string Format_DataMatrix_Placeholder => ResourceManager.GetString("Format_DataMatrix_Placeholder", resourceCulture);
        internal static string Format_Pdf417_Name => ResourceManager.GetString("Format_Pdf417_Name", resourceCulture);
        internal static string Format_Aztec_Name => ResourceManager.GetString("Format_Aztec_Name", resourceCulture);

        internal static string FormatValidate_NonAscii => ResourceManager.GetString("FormatValidate_NonAscii", resourceCulture);
        internal static string FormatValidate_Code39 => ResourceManager.GetString("FormatValidate_Code39", resourceCulture);
        internal static string FormatValidate_Codabar => ResourceManager.GetString("FormatValidate_Codabar", resourceCulture);
        internal static string FormatValidate_ItfDigitsOnly => ResourceManager.GetString("FormatValidate_ItfDigitsOnly", resourceCulture);
        internal static string FormatValidate_ItfEvenLength => ResourceManager.GetString("FormatValidate_ItfEvenLength", resourceCulture);
        internal static string FormatValidate_NumericOnly => ResourceManager.GetString("FormatValidate_NumericOnly", resourceCulture);
        internal static string FormatValidate_LengthMismatch => ResourceManager.GetString("FormatValidate_LengthMismatch", resourceCulture);
    }
}
