<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>BarcodeList</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- BarcodeList(メインアプリ)からinternalなAppResourcesへアクセスできるようにする -->
		<InternalsVisibleTo Include="BarcodeList" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ZXing.Net.Maui" Version="0.8.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Strings\AppResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AppResources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Strings\AppResources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>AppResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
